/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slides;

/**
 *
 * @author nuraz
 */
public class slide3_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form slide3_dashboard
     */
    public slide3_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typing_keluar = new javax.swing.JLabel();
        typing_nootif = new javax.swing.JLabel();
        typing_karyawan = new javax.swing.JLabel();
        typing_laporan = new javax.swing.JLabel();
        typing_transaksi = new javax.swing.JLabel();
        typing_pesanan = new javax.swing.JLabel();
        typing_dashboard = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        icon_laporan = new javax.swing.JLabel();
        icon_karyawan = new javax.swing.JLabel();
        icon_notifikasi = new javax.swing.JLabel();
        icon_keluar = new javax.swing.JLabel();
        icon_transaksi = new javax.swing.JLabel();
        icon_pesanan = new javax.swing.JLabel();
        icon_dashboard = new javax.swing.JLabel();
        pend_bulanan = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        background_putih = new javax.swing.JLabel();
        background_kuning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typing_keluar.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_keluar.setForeground(new java.awt.Color(242, 242, 242));
        typing_keluar.setText("Keluar");
        getContentPane().add(typing_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 740, -1, 30));

        typing_nootif.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_nootif.setForeground(new java.awt.Color(242, 242, 242));
        typing_nootif.setText("Notifikasi");
        getContentPane().add(typing_nootif, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, -1, 40));

        typing_karyawan.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_karyawan.setForeground(new java.awt.Color(242, 242, 242));
        typing_karyawan.setText("Karyawan");
        getContentPane().add(typing_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, 30));

        typing_laporan.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_laporan.setForeground(new java.awt.Color(242, 242, 242));
        typing_laporan.setText("Laporan");
        getContentPane().add(typing_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, 30));

        typing_transaksi.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_transaksi.setForeground(new java.awt.Color(242, 242, 242));
        typing_transaksi.setText("Transaksi");
        getContentPane().add(typing_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 30));

        typing_pesanan.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_pesanan.setForeground(new java.awt.Color(242, 242, 242));
        typing_pesanan.setText("Pesanan");
        getContentPane().add(typing_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 30));

        typing_dashboard.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        typing_dashboard.setForeground(new java.awt.Color(242, 242, 242));
        typing_dashboard.setText("Dashboard");
        getContentPane().add(typing_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 252, -1, 30));

        welcome.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(242, 242, 242));
        welcome.setText("Welcome, Elsa");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/profil.png"))); // NOI18N
        getContentPane().add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_laporan.png"))); // NOI18N
        getContentPane().add(icon_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -150, -1, -1));

        icon_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_karyawan.png"))); // NOI18N
        getContentPane().add(icon_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -160, -1, -1));

        icon_notifikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_notif.png"))); // NOI18N
        getContentPane().add(icon_notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -170, -1, -1));

        icon_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_keluar.png"))); // NOI18N
        getContentPane().add(icon_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -180, -1, -1));

        icon_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_transaksi.png"))); // NOI18N
        getContentPane().add(icon_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -140, -1, -1));

        icon_pesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_pesanan.png"))); // NOI18N
        icon_pesanan.setText("jLabel2");
        getContentPane().add(icon_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -140, -1, -1));

        icon_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/icon_dashboard.png"))); // NOI18N
        icon_dashboard.setText("jLabel2");
        getContentPane().add(icon_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pend_bulanan.setViewportView(jTable1);

        getContentPane().add(pend_bulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 460, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kamis, 20 Februari 2025");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        dashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        dashboard.setForeground(new java.awt.Color(0, 102, 102));
        dashboard.setText("Dashboard");
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 530, 60));

        background_putih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide3_dashboard/background putih.png"))); // NOI18N
        getContentPane().add(background_putih, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background_kuning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/background kuning.png"))); // NOI18N
        getContentPane().add(background_kuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slide3_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slide3_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slide3_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slide3_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new slide3_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_kuning;
    private javax.swing.JLabel background_putih;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel icon_dashboard;
    private javax.swing.JLabel icon_karyawan;
    private javax.swing.JLabel icon_keluar;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel icon_notifikasi;
    private javax.swing.JLabel icon_pesanan;
    private javax.swing.JLabel icon_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane pend_bulanan;
    private javax.swing.JLabel profil;
    private javax.swing.JLabel typing_dashboard;
    private javax.swing.JLabel typing_karyawan;
    private javax.swing.JLabel typing_keluar;
    private javax.swing.JLabel typing_laporan;
    private javax.swing.JLabel typing_nootif;
    private javax.swing.JLabel typing_pesanan;
    private javax.swing.JLabel typing_transaksi;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
