/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slides;

/**
 *
 * @author nuraz
 */
public class slide2_signup extends javax.swing.JFrame {

    /**
     * Creates new form slide2_signup
     */
    public slide2_signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daftar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        type2 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        passw2 = new javax.swing.JTextField();
        passw1 = new javax.swing.JTextField();
        membuatpw = new javax.swing.JLabel();
        eemail = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        daftarakun = new javax.swing.JLabel();
        logo_soclean = new javax.swing.JLabel();
        bubble = new javax.swing.JLabel();
        background_hijau = new javax.swing.JLabel();
        background_kuning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftar.setBackground(new java.awt.Color(239, 196, 9));
        daftar.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        daftar.setText("Daftar");
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 590, 170, 40));

        jCheckBox1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(242, 242, 242));
        jCheckBox1.setText("Saya membaca, mengerti dan menyetujui syarat dan \nketentuan serta kebijakan privasi yang berlaku."); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 650, 80));

        type2.setForeground(new java.awt.Color(255, 255, 255));
        type2.setText("Kata sandi harus berisi 8 huruf kecil dan kapital, angka dan juga simbol (!@#$%^&*,.?)");
        getContentPane().add(type2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, -1, -1));

        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Pastikan Anda memasukkan kata sandi yang tepat!");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 470, -1, -1));

        passw2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        passw2.setForeground(new java.awt.Color(0, 102, 102));
        passw2.setText("Kata Sandi");
        getContentPane().add(passw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 360, 50));

        passw1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        passw1.setForeground(new java.awt.Color(0, 102, 102));
        passw1.setText("Konfirmasi Kata Sandi");
        getContentPane().add(passw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, 360, 50));

        membuatpw.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        membuatpw.setForeground(new java.awt.Color(255, 255, 255));
        membuatpw.setText("Membuat Kata Sandi");
        getContentPane().add(membuatpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 240, 440, 60));

        eemail.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        eemail.setForeground(new java.awt.Color(0, 102, 102));
        eemail.setText("No. Hp");
        getContentPane().add(eemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 360, 50));

        nohp.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        nohp.setForeground(new java.awt.Color(0, 102, 102));
        nohp.setText("Email");
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 360, 50));

        nama.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 102, 102));
        nama.setText("Nama");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 360, 50));

        daftarakun.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        daftarakun.setForeground(new java.awt.Color(0, 102, 102));
        daftarakun.setText("Daftar Akun SoClean Laundry");
        getContentPane().add(daftarakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 630, 60));

        logo_soclean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/logo soclean.png"))); // NOI18N
        getContentPane().add(logo_soclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 20, -1, -1));

        bubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/bubble.png"))); // NOI18N
        getContentPane().add(bubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, -1, -1));

        background_hijau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/background hijau.png"))); // NOI18N
        getContentPane().add(background_hijau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -120, -1, 1030));

        background_kuning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/background kuning.png"))); // NOI18N
        getContentPane().add(background_kuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 0, 2110, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slide2_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slide2_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slide2_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slide2_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new slide2_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_hijau;
    private javax.swing.JLabel background_kuning;
    private javax.swing.JLabel bubble;
    private javax.swing.JButton daftar;
    private javax.swing.JLabel daftarakun;
    private javax.swing.JTextField eemail;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel logo_soclean;
    private javax.swing.JLabel membuatpw;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField passw1;
    private javax.swing.JTextField passw2;
    private javax.swing.JLabel type;
    private javax.swing.JLabel type2;
    // End of variables declaration//GEN-END:variables
}
