/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slides;

/**
 *
 * @author nuraz
 */
public class slide1_login extends javax.swing.JFrame {

    /**
     * Creates new form slide1_login
     */
    public slide1_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lupasandi = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        pw = new javax.swing.JPasswordField();
        daftar = new javax.swing.JButton();
        Masuk = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        masukkeakun = new javax.swing.JLabel();
        logo_soclean = new javax.swing.JLabel();
        tidakmemilikiakun = new javax.swing.JLabel();
        laundry = new javax.swing.JLabel();
        selamatdatang = new javax.swing.JLabel();
        bubble = new javax.swing.JLabel();
        background_hijau = new javax.swing.JLabel();
        background_kuning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lupasandi.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lupasandi.setForeground(new java.awt.Color(242, 242, 242));
        lupasandi.setText("Lupa Kata sandi ?");
        getContentPane().add(lupasandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, -1, 30));

        jCheckBox1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(242, 242, 242));
        jCheckBox1.setText("Ingat Saya?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, -1));

        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 400, 50));

        daftar.setBackground(new java.awt.Color(239, 196, 9));
        daftar.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        daftar.setText("Daftar");
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 690, 170, 50));

        Masuk.setBackground(new java.awt.Color(0, 102, 102));
        Masuk.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        Masuk.setForeground(new java.awt.Color(255, 255, 255));
        Masuk.setText("Masuk");
        getContentPane().add(Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 170, 50));

        user.setForeground(new java.awt.Color(0, 102, 102));
        user.setText("Username");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 400, 50));

        masukkeakun.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        masukkeakun.setForeground(new java.awt.Color(0, 102, 102));
        masukkeakun.setText("Masuk ke Akun Anda");
        getContentPane().add(masukkeakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 530, 60));

        logo_soclean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/logo soclean.png"))); // NOI18N
        getContentPane().add(logo_soclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, -1, -1));

        tidakmemilikiakun.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        tidakmemilikiakun.setForeground(new java.awt.Color(255, 255, 255));
        tidakmemilikiakun.setText("Tidak Memiliki Akun?");
        getContentPane().add(tidakmemilikiakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 660, -1, -1));

        laundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/laundry.png"))); // NOI18N
        getContentPane().add(laundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        selamatdatang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/selamatdatang.png"))); // NOI18N
        selamatdatang.setText("jLabel2");
        getContentPane().add(selamatdatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        bubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/bubble.png"))); // NOI18N
        getContentPane().add(bubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        background_hijau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/background hijau.png"))); // NOI18N
        getContentPane().add(background_hijau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -120, -1, 1030));

        background_kuning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/slide1_login/background kuning.png"))); // NOI18N
        getContentPane().add(background_kuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 0, 2110, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slide1_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slide1_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slide1_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slide1_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new slide1_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Masuk;
    private javax.swing.JLabel background_hijau;
    private javax.swing.JLabel background_kuning;
    private javax.swing.JLabel bubble;
    private javax.swing.JButton daftar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel laundry;
    private javax.swing.JLabel logo_soclean;
    private javax.swing.JLabel lupasandi;
    private javax.swing.JLabel masukkeakun;
    private javax.swing.JPasswordField pw;
    private javax.swing.JLabel selamatdatang;
    private javax.swing.JLabel tidakmemilikiakun;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
